# Używamy oficjalnego obrazu Node.js w wersji 20 na bazie Alpine Linux
# Alpine to lekka dystrybucja, która przyspiesza budowanie
image: node:20-alpine

.rules:
  feature_branch: &feature
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^(production|staging)$/
        when: never
      - when: always

# Domyślna konfiguracja dla wszystkich jobów
default:
  before_script:
    - yarn install

# Definicja etapów pipeline'u
stages:
  - test

test:
  <<: *feature
  stage: test
  script:
    - yarn test
  coverage: '/All files\s*\|[^|]*\|[^|]*\|[^|]*\|\s*([\d\.]+)\s*\|/'
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
