import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Home, Info, Phone, ShoppingCart } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        {/* Sticky Header */}
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 items-center">
            <div className="mr-4 hidden md:flex">
              <Link className="mr-6 flex items-center space-x-2" href="/">
                <ShoppingCart className="h-6 w-6" />
                <span className="hidden font-bold sm:inline-block">ACME Store</span>
              </Link>
            </div>
            <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
              <nav className="flex items-center space-x-6">
                <Link href="/" className="text-sm font-medium transition-colors hover:text-primary">
                  <Home className="h-4 w-4" />
                  <span className="sr-only">Home</span>
                </Link>
                <Link
                  href="/about"
                  className="text-sm font-medium transition-colors hover:text-primary"
                >
                  <Info className="h-4 w-4" />
                  <span className="sr-only">About</span>
                </Link>
                <Link
                  href="/contact"
                  className="text-sm font-medium transition-colors hover:text-primary"
                >
                  <Phone className="h-4 w-4" />
                  <span className="sr-only">Contact</span>
                </Link>
                <Link href="/purchase">
                  <Button size="sm">Buy Now</Button>
                </Link>
              </nav>
            </div>
          </div>
        </header>

        <main className="space-section container mx-auto flex-1 p-4">{children}</main>

        {/* Footer */}
        <footer className="w-full bg-gray-100 py-6 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
              <div className="flex flex-col items-center gap-4 px-8 md:flex-row md:gap-2 md:px-0">
                <ShoppingCart className="h-6 w-6" />
                <p className="text-center text-sm leading-loose text-gray-600 dark:text-gray-400 md:text-left">
                  © 2023 ACME Store. All rights reserved.
                </p>
              </div>
              <div className="flex gap-4">
                <Link
                  href="/terms"
                  className="text-sm text-gray-600 hover:underline dark:text-gray-400"
                >
                  Terms
                </Link>
                <Link
                  href="/privacy"
                  className="text-sm text-gray-600 hover:underline dark:text-gray-400"
                >
                  Privacy
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}
